language: java
jdk: oraclejdk8

services:
  - docker

before_install:
  - docker login "$DOCKER_REPOSITORY" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  provider: script
  skip_cleanup: true
  script: sh docker/deploy.sh
  on:
    branch: master
