language: java
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.m2

env:
  - spring.profiles.active=buildDocker

services:
  - docker

before_install:
  - docker login "$DOCKER_REPOSITORY" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  provider: script
  skip_cleanup: true
  script: sh docker/deploy.sh
  on:
    branch: master
